language: node_js
sudo: false
node_js:
  - node
  - '10'
os:
  - linux
  - osx
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn build
  - yarn lint
  - yarn test
